### ISSUE TITLE
You need to specify UDP to start the container

### ISSUE THREAD

**Issue by Soren90** [spritsail/fivem#1]
Hey,

I've used this container and it works fine. But you should add this to the example:

docker run -d \
  --name FiveM \
  --restart=on-failure \
  -e LICENCE_KEY=<your-license-here>
  -p 30120:30120 \
  -p 30120:30120/udp \
  -v /volumes/fivem:/config \
  spritsail/fivem

If you don't add the UDP, you will be able to find the server, but not connect to it.

**Comment by frebib** [comment]
:+1:  I'll add it :)
Thanks
