### ISSUE TITLE
Updating to 1629 produces error and immediate crash

### ISSUE THREAD

**Issue by Phyremaster** [spritsail/fivem#10]
The server was working fine until Watchtower automatically updated the container to version 1629. Now, every time that it is started, the container spits out `Could not find component cache storage file (components.json).` (and nothing else) in the logs and immediately crashes. Switching back to the previous version (1626) fixed the issue completely. You might want to push that version to the `latest` tag until this issue is fixed, as I highly doubt that I will be the only user affected by this bug.

**Comment by frebib** [comment]
Would you mind providing an example run line/compose excerpt so I can reproduce this? We'll revert for now and try work out what's the wrong :)

**Comment by frebib** [comment]
Looks like it was a simple workdir issue. Please lmk if the current build fixes your issue, or re-open this if it doesn't!

**Comment by Phyremaster** [comment]
I had to wait for the server to empty, but I updated back to the `latest` tag, and it work just fine now. Thanks!
