### ISSUE TITLE
Couldn't find resources

### ISSUE THREAD

**Issue by bbhoss** [spritsail/fivem#11]
I'm using the provided `docker-compose.yml` to run the fivem server. I set the license key and modified the network forwards to use my desired ip address for the server, otherwise it is as included. When I start fivem, the server.cfg and resources get created in the directory I'm mounting as a volume, but it seems to complain that it can't find various resources. It's unclear whether I'm missing something extremely basic or if this is just a bug. Here's the output
```
Resolved live-internal.fivem.net:30110 to 178.32.9.100:30110
Creating script environments for _cfx_internal
Found new resource webadmin in /opt/cfx-server/citizen//system_resources//webadmin
Couldn't find resource sessionmanager.
Creating script environments for webadmin
Instantiated instance of script FxWebAdmin.BaseServer.
Instantiated instance of script FxWebAdmin.HttpServer+HttpServerScript.
Started resource webadmin
Couldn't find resource playernames.
Couldn't find resource mapmanager.
Couldn't find resource chat.
Couldn't find resource spawnmanager.
Couldn't find resource sessionmanager.
Couldn't find resource fivem.
Couldn't find resource hardcap.
Couldn't find resource rconlog.
Couldn't find resource scoreboard.
Authenticating server license key...
Server license key authentication succeeded. Welcome!
cfx> Sending heartbeat to live-internal.fivem.net:30110
Authenticating with Nucleus...
server thread hitch warning: timer interval of 3862 milliseconds
        fff
  cccc ff   xx  xx     rr rr    eee
cc     ffff   xx       rrr  r ee   e
cc     ff     xx   ... rr     eeeee
 ccccc ff   xx  xx ... rr      eeeee

Authenticated with cfx.re Nucleus: https://bbhoss-4gley5.cfx.re/
Saved GeoLite2-Country to /opt/cfx-server/citizen//system_resources//webadmin/GeoLite2-Country.mmdb.
Sending heartbeat to live-internal.fivem.net:30110
```

**Comment by Phyremaster** [comment]
I have the same issue, and my server worked just fine on 1626, so I'm going to revert to that tag (and I recommend you do the same). Unfortunately, I'm not sure which of the recent commits resulted in this issue, but I would assume that FiveM 1629's file structure differs from the previous structure (given that no recent commits have changed the file structure of the container significantly).

**Comment by bbhoss** [comment]
Thanks a ton, I've pinned to 1626 and it seems to be working. I look forward to updating to latest once this is resolved.

**Comment by frebib** [comment]
So I can't quite work out what they changed but from what I can tell, the latest build works just fine for me? Did you pull?

```
frebib@frebib-PC /t/tmp.6vt2z6l0EI> cat docker-compose.yml
version: '3'

services:
  fivem:
    image: spritsail/fivem
    container_name: fivem
    restart: on-failure
    stdin_open: true
    tty: true
    volumes:
      - .:/config
    ports:
      - "30120:30120"
      - "30120:30120/udp"
    environment:
      LICENCE_KEY: <snip>
frebib@frebib-PC /t/tmp.6vt2z6l0EI> docker-compose pull
Pulling fivem ... done
frebib@frebib-PC /t/tmp.6vt2z6l0EI> docker-compose up
Recreating fivem ... done
Attaching to fivem
fivem    | Resolved live-internal.fivem.net:30110 to 178.32.9.100:30110
fivem    | Creating script environments for _cfx_internal
fivem    | Found new resource webadmin in /opt/cfx-server/citizen//system_resources//webadmin
fivem    | Couldn't find resource sessionmanager.
fivem    | Creating script environments for webadmin
fivem    | Instantiated instance of script FxWebAdmin.BaseServer.
fivem    | Instantiated instance of script FxWebAdmin.HttpServer+HttpServerScript.
fivem    | Started resource webadmin
fivem    | No such config file: /config/server.cfg
fivem    | Authenticating server license key...
fivem    | Server license key authentication succeeded. Welcome!
fivem    | cfx> Sending heartbeat to live-internal.fivem.net:30110
fivem    | Authenticating with Nucleus...
fivem    | server thread hitch warning: timer interval of 1083 milliseconds
fivem    |         fff
fivem    |   cccc ff   xx  xx     rr rr    eee
fivem    | cc     ffff   xx       rrr  r ee   e
fivem    | cc     ff     xx   ... rr     eeeee
fivem    |  ccccc ff   xx  xx ... rr      eeeee
fivem    |
fivem    | Authenticated with cfx.re Nucleus: https://frebib-n4ayev.cfx.re/
fivem    | Saved GeoLite2-Country to /opt/cfx-server/citizen//system_resources//webadmin/GeoLite2-Country.mmdb.
^C
Gracefully stopping... (press Ctrl+C again to force)
Stopping fivem   ... done
```

**Comment by Phyremaster** [comment]
I apologize for not responding to this sooner; the server that I am hosting needs to remain on 1626 for other reasons, so I wasn't paying attention to this issue. @frebib The output you posted indicates the same exact error that we encountered (note the line `fivem    | Couldn't find resource sessionmanager.`, and the fact that the only resource that actually loaded was `webadmin`). The issue is not in the `docker-compose.yml`, because I had the issue without using compose at all.

**Comment by frebib** [comment]
According to the documentation, you should `cd server-data`, but if the cwd is not `/opt/cfx-server` then it fails to find the components.json. :man_shrugging: 
https://docs.fivem.net/server-manual/setting-up-a-server/

**Comment by Adam-Ant** [comment]
I think I've now solved this one. A combination of a workaround we implemented coming back to bite us, and some unannounced changes to the server.cfg file by the FiveM team was the root cause. If you are using existing configs, please note the [changes made to server.cfg](https://github.com/spritsail/fivem/commit/26c3ff27bc90114104fc6ace9b7366440880473e#diff-8e6a3ff3341b06217162b798e5700726L6-R18)

I'll leave this issue open for a few days, as although the server logs look good, I don't have access to a FiveM client right now to verify clients can connect. @bbhoss or @Phyremaster could you confirm if possible? Thanks
