### ISSUE TITLE
Add an additional image for the monitor (txAdmin)

### ISSUE THREAD

**Issue by izio38** [spritsail/fivem#17]
Hi,

I'm using your docker image for all of my servers. It's really cool, but in-order-to use the (new) monitor resource, it need the `./FXServer` to be run without any `+exec`, it looks like this :

![image](https://user-images.githubusercontent.com/9900846/85230302-8483b080-b3ef-11ea-9116-8adce8668591.png)

If we want to have this thing with your image, I have to run : `docker-compose exec fivem sh` then go to : `/opt/cfx-server` and then run the `./FXServer` (and the license key obviously).

The console output this : 
```
  _______  ______                           
 |  ___\ \/ / ___|  ___ _ ____   _____ _ __ 
 | |_   \  /\___ \ / _ \ '__\ \ / / _ \ '__|
 |  _|  /  \ ___) |  __/ |   \ V /  __/ |   
 |_|   /_/\_\____/ \___|_|    \_/ \___|_|   
-------------------------------- monitor ---

Creating script environments for _cfx_internal
Creating script environments for monitor
[txAdmin] Version ,2.5.1 using data path '/txData'
[txAdmin] >> Starting profile default
[txAdmin:ConfigVault] Started
[txAdmin:Authenticator] Started
[txAdmin:DiscordBot] Disabled by the config file.
[txAdmin:FXRunner] Started
[txAdmin:Logger] Started
[txAdmin:Translator] Started
[txAdmin:Monitor] Started
[txAdmin:PlayerController] Started
[txAdmin:WebServer] Listening at  http://localhost:40120/ 
[txAdmin:WebServer] Listening at  https://xxxx-xxxxx-xxxxxx-xxxxx.users.cfx.re/ 
```

It's a really cool feature that I think it could be great to have.

In-order-to do so. I think we just have to build another image like `fxserver-monitor`, that only launch the `FXServer` program only with the license key argument.

What do you think ?

**Comment by Adam-Ant** [comment]
That panel looks interesting, it's certainly something we can look at supporting. Instead of a separate image, I'd probably prefer an env var that disables the +exec statement. Is txAdmin happy with the +set citizen_dir argument - eg, would the below work?

`FXServer +set citizen_dir /opt/cfx-server/citizen/ +set sv_licenseKey ${LICENCE_KEY} <user provided args for txAdmin>`

**Comment by frebib** [comment]
I've made a PR to allow disabling the default options (#18). If you want to try it out I pushed it to Docker Hub under `spritsail/fivem:optional-option`

**Comment by izio38** [comment]
> That panel looks interesting, it's certainly something we can look at supporting. Instead of a separate image, I'd probably prefer an env var that disables the +exec statement. Is txAdmin happy with the +set citizen_dir argument - eg, would the below work?
> 
> `FXServer +set citizen_dir /opt/cfx-server/citizen/ +set sv_licenseKey ${LICENCE_KEY} <user provided args for txAdmin>`

I think so.



> I've made a PR to allow disabling the default options (#18). If you want to try it out I pushed it to Docker Hub under `spritsail/fivem:optional-option`

I'm testing it right now.

**Comment by izio38** [comment]
@frebib I have this log : `fivem    | /usr/bin/entrypoint: line 26: CONFIG_ARGS+=+set sv_licenseKey 0g3a7rlmvha9sglvks7fd917lacwwn04: not found`

The server is launching but not in monitor mode (aka : `txAdmin requires to be launched from inside FXServer in monitor mode, to do that, just execute the run.sh or FXServer.exe without any +exec arguments.`)

**Comment by frebib** [comment]
Ah right of course, that's because I didn't put any spaces in the script, oops. I'll push another fixup and you can give that a go. If that doesn't work, I'll switch it to bash arrays which will definitely work

**Comment by izio38** [comment]
Alright, let me know when the push is done, I'll test it, if you want to try it out yourself, I use this `docker-compose` file : 

```yaml
  fivem-monitor:
    image: spritsail/fivem:optional-options
    container_name: fivem-monitor
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ./config:/config
    ports:
      - "30120:30120"
      - "30120:30120/udp"
    environment:
      LICENCE_KEY: xxxxxxxxxxxxxxxxxxxxxx
```

**Comment by frebib** [comment]
Oh, the CI never ran :thinking: 
Lemme poke it, then it should be up in a minute or two

**Comment by frebib** [comment]
Running with this config, I think it does what you want
```
services:
  fivem-monitor:
    image: spritsail/fivem:optional-options
    stdin_open: true
    tty: true
    environment:
      DEBUG: '1'
      NO_DEFAULT_CONFIG: '1'
      LICENCE_KEY: <snip>
```
Let me know if not. You can drop the DEBUG` envvar too, it's useful for seeing what commands are run in the entrypoint.

```
...
fivem-monitor_1  | + exec /opt/cfx-server/FXServer +set citizen_dir /opt/cfx-server/citizen/ +set sv_licenseKey <snip>
fivem-monitor_1  |   _______  ______
fivem-monitor_1  |  |  ___\ \/ / ___|  ___ _ ____   _____ _ __
fivem-monitor_1  |  | |_   \  /\___ \ / _ \ '__\ \ / / _ \ '__|
fivem-monitor_1  |  |  _|  /  \ ___) |  __/ |   \ V /  __/ |
fivem-monitor_1  |  |_|   /_/\_\____/ \___|_|    \_/ \___|_|
fivem-monitor_1  | -------------------------------- monitor ---
fivem-monitor_1  |
fivem-monitor_1  | Creating script environments for _cfx_internal
fivem-monitor_1  | Creating script environments for monitor
fivem-monitor_1  | [txAdmin] This version of txAdmin is too much outdated.
fivem-monitor_1  | [txAdmin] Please update as soon as possible.
fivem-monitor_1  | [txAdmin] Version 2.5.1 using data path '/txData'
fivem-monitor_1  | [txAdmin] >> Starting profile default
fivem-monitor_1  | [txAdmin:SetupProfile] =========================================================
fivem-monitor_1  | [txAdmin:SetupProfile] Creating new profile folder...
fivem-monitor_1  | [txAdmin:SetupProfile] Server profile was saved in '/txData/default'
fivem-monitor_1  | [txAdmin:SetupProfile] =========================================================
fivem-monitor_1  | [txAdmin:ConfigVault] Started
fivem-monitor_1  | [txAdmin:Authenticator] Started
fivem-monitor_1  | [txAdmin:Authenticator] ==========================================
fivem-monitor_1  | [txAdmin:Authenticator] ==> Admins file not found.
fivem-monitor_1  | [txAdmin:Authenticator] ==> PIN to add a master account:  0000
fivem-monitor_1  | [txAdmin:Authenticator] ==========================================
fivem-monitor_1  | [txAdmin:DiscordBot] Disabled by the config file.
fivem-monitor_1  | [txAdmin:FXRunner] Started
fivem-monitor_1  | [txAdmin:Logger] Started
fivem-monitor_1  | [txAdmin:Translator] Started
fivem-monitor_1  | [txAdmin:Monitor] Started
fivem-monitor_1  | [txAdmin:PlayerController] Started
fivem-monitor_1  | [txAdmin:WebServer] Listening at  http://localhost:40120/
fivem-monitor_1  | [txAdmin:WebServer] Listening at  https://<snip>.users.cfx.re/
```

**Comment by izio38** [comment]
![image](https://user-images.githubusercontent.com/9900846/86143950-5ab84100-baf5-11ea-81c5-2e8bb61e9999.png)

Simply awesome :)

**Comment by frebib** [comment]
So this is good? Want me to merge the PR?

**Comment by izio38** [comment]
It's perfecly fine, I also tried without `NO_DEFAULT_CONFIG`, it's still working as usual :)

**Comment by frebib** [comment]
Without `NO_DEFAULT_CONFIG` is the behaviour before, so it should not be any different.
I've merged the PR into master so I'll delete the other Docker image
