### ISSUE TITLE
Execute console commands

### ISSUE THREAD

**Issue by aogmike** [spritsail/fivem#22]
How Can I execute console commands?
Or how to I access the FiveM console?

**Comment by frebib** [comment]
https://docs.docker.com/engine/reference/commandline/exec/

Something like `docker exec -ti <container-name> sh` will get you a shell inside the container.

To interact with the running fivem process directly, attach to the container with `docker attach <container-name>` and detach with `Ctrl+P Ctrl+Q`
https://docs.docker.com/engine/reference/commandline/attach/

**Comment by aogmike** [comment]
I used docker attach <container-name> but the say command for example is not working

**Comment by frebib** [comment]
Did you create the container with a pseudo-tty either `docker run -ti` or `tty: true` if you're using docker-compose.

**Comment by nerdfoundrygaming** [comment]
I know this is an old issue, but enabling `tty` and `stdin_open` aren't allowing input when attached.

**Comment by maejok-xx** [comment]
still an issue
