### ISSUE TITLE
TXAdmin support ? 

### ISSUE THREAD

**Issue by L4wlz** [spritsail/fivem#34]
Hi there.. Great job.. :) 
What about TXAdmin support on this docker ? can this be added somehow ?

**Comment by izio38** [comment]
#17

**Comment by sesipod** [comment]
This would be nice / launched the latest docker file yet no txAmin is included.

**Comment by onvrb** [comment]
txAdmin is included (in the sever artifacts themselves), however you need to expose the port 40120 (if you expose it to the host, make sure it's not accessible from the internet) or reverse proxy through nginx.

This has been discussed for a while, see https://github.com/spritsail/fivem/pull/23

@frebib refuses to accept the commit, who knows why.

**Comment by izio38** [comment]
Are you guys reading the #17 ???
It is already working.

**Comment by frebib** [comment]
Closing as this should be working as implemented in #17.
