### ISSUE TITLE
Adding enforceGameBuild Env

### ISSUE THREAD

**Issue by JoeSzymkowiczFiveM** [spritsail/fivem#39]
Theres a launch argument, +set sv_enforceGameBuild 2060, that I would like to use with the fivem container. Is there any way to enable this without modifying the docker config?

**Comment by JoeSzymkowiczFiveM** [comment]
After talking to some other server admins, it seems this option is fairly popular, and might even be better as a docker env variable. Can this be done? To be clear, the command is +set sv_enforceGameBuild, "2060" is simply the value passed to it, among other versions.

**Comment by JoeSzymkowiczFiveM** [comment]
Closing as I've submitted https://github.com/spritsail/fivem/pull/40 for consideration.

**Comment by frebib** [comment]
Hey, I read this and totally forgot to reply, apologies!

You can provide additional arguments to cfx-server with the container cmdline:
```
docker run ... spritsail/fivem +set sv_enforceGameBuild 2060
```
or
```
services:
  fivem:
    image: spritsail/fivem
    cmd: [+set, sv_enforceGameBuild, 2060]
    ...
```
so your PR shouldn't be needed. Let me know if it works
