### ISSUE TITLE
I am trying restart script in fivem  start.bat  but i seen couldn't find resource script

### ISSUE THREAD

**Issue by kafkaskrtl** [spritsail/fivem#42]

**Comment by Adam-Ant** [comment]
Hi,
Please could you give us a little bit more information on what you are trying to accomplish & what you have done so far. A docker run example, a log output and a general description of what your goal is would be a good start.

As an aside - please have a look through some best practices of opening GitHub issues. Github themselves have an excellent guide [here](https://guides.github.com/features/issues/). Its considered quite bad form to open multiple issues for the same problem, and even a brief description of whats happening can go a long way to help maintainers help you!
