### ISSUE TITLE
Building resource webpack failed. Error data: yarn failed.

### ISSUE THREAD

**Issue by Tetrafix** [spritsail/fivem#44]
So I am trying to create a new server. I am of a fresh download and as soon as I booted the server up I keep getting an error thrown for 
Building resource webpack failed. 
Error data: yarn failed.
Does anyone know why this may be happening and how to fix it. I saw in the last cfx patch they updated yarn lock would that affect it? Screenshot of the command prompt below.
![Screenshot 2021-05-16 103927](https://user-images.githubusercontent.com/84279617/118401271-09447200-b633-11eb-8bae-094cf192fa6a.png)

**Comment by Tetrafix** [comment]
Also apologies if I am in the wrong place.

**Comment by frebib** [comment]
Try pulling an older tag for now. This is most likely broken upstream in the latest build. I'll see if it's been fixed upstream yet
