### ISSUE TITLE
No archive resource in Dockerfile

### ISSUE THREAD

**Issue by phuthai** [spritsail/fivem#46]
hi there

Seem Dockerfile location change structure (no archive resource) , 
please help me to figure out how to build docker image file.
=====
&& wget -O- http://github.com/citizenfx/cfx-server-data/archive/${DATA_VER}.tar.gz \
        | tar xz --strip-components=1 -C opt/cfx-server-data \
=====

Thank you advise
Prasong P

**Comment by frebib** [comment]
This Dockerfile builds correctly for me (see CI: https://drone.spritsail.io/spritsail/fivem/108/1/2)
Can you post the error you're seeing?
