### ISSUE TITLE
Outdated version

### ISSUE THREAD

**Issue by Sigri44** [spritsail/fivem#47]
When we use the last image version :

![image](https://user-images.githubusercontent.com/9304947/133932045-0f50ffef-cdf5-4a3a-890a-d03f93e8a939.png)

**Comment by frebib** [comment]
It seems we don't have automation to bump the version of the fivem build automatically, only for the cfx-server-data. I've bumped to the latest recommended now. 

For reference, the build numbers/hashes are found here: https://runtime.fivem.net/artifacts/fivem/build_proot_linux/master/ as linked from that aka.cfx.re/eol page. Feel free to send a PR if we're lagging behind on releases here
