### ISSUE TITLE
[QUESTION] Could the webUI be added back to this?

### ISSUE THREAD

**Issue by hax4dazy** [spritsail/fivem#48]
So I'm really used to having the web UI like shown in the [docs](https://docs.fivem.net/docs/server-manual/setting-up-a-server/) and I'm wondering if we could have that here too?

**Comment by Adam-Ant** [comment]
Apologies for necro'ing this issue - this is already possible in the image. I've added a note to the readme about the best way to go about enabling the web UI.

**Comment by hax4dazy** [comment]
Thanks ❤️
