### ISSUE TITLE
Fivem problem

### ISSUE THREAD

**Issue by Mrpingvin14** [spritsail/fivem#51]
What can I do about it? 

[         script:yarn] Error: [yarn] F:\txData\CFXDefault_374651.base\resources\[system]\[builders]\yarn\yarn_cli.js:89123
[         script:yarn]     lock.compromised(err);
[         script:yarn]          ^
[         script:yarn] 
[         script:yarn] TypeError: lock.compromised is not a function
[         script:yarn]     at compromisedLock (F:\txData\CFXDefault_374651.base\resources\[system]\[builders]\yarn\yarn_cli.js:89123:10)
[         script:yarn]     at F:\txData\CFXDefault_374651.base\resources\[system]\[builders]\yarn\yarn_cli.js:89075:24
[         script:yarn]     at FSReqCallback.oncomplete (node:fs:188:23)

**Comment by adagardi** [comment]
> What can I do about it?
> 
> [ script:yarn] Error: [yarn] F:\txData\CFXDefault_374651.base\resources[system][builders]\yarn\yarn_cli.js:89123 [ script:yarn] lock.compromised(err); [ script:yarn] ^ [ script:yarn] [ script:yarn] TypeError: lock.compromised is not a function [ script:yarn] at compromisedLock (F:\txData\CFXDefault_374651.base\resources[system][builders]\yarn\yarn_cli.js:89123:10) [ script:yarn] at F:\txData\CFXDefault_374651.base\resources[system][builders]\yarn\yarn_cli.js:89075:24 [ script:yarn] at FSReqCallback.oncomplete (node:fs:188:23)

**Comment by Adam-Ant** [comment]
I suspect this is a bug in the upstream FiveM code. We've just bumped to the latest version (5985) - please reopen this issue if this still occurs.
