### ISSUE TITLE
[ citizen-server-impl] Couldn't find resource category [vehicles]. 

### ISSUE THREAD

**Issue by Hugo3584** [spritsail/fivem#60]
Can not find my vehicle resource please help tryed everything

![Screenshot_1](https://user-images.githubusercontent.com/121652048/210031017-5ce5b1ab-dc36-4114-8f14-8231c97197a3.png)
![Screenshot_2](https://user-images.githubusercontent.com/121652048/210031021-b6118fcc-8b7a-
![Screenshot_3](https://user-images.githubusercontent.com/121652048/210031024-f376e971-4df9-4276-9577-8d29774020cf.png)
44c9-8291-2367d34924b2.png)
![Screenshot_4](https://user-images.githubusercontent.com/121652048/210031031-de490aad-1f79-40f2-907b-be5e15d8d32a.png)

**Comment by frebib** [comment]
This isn't a fivem support forum. Use the fivem forum for help https://forum.cfx.re/
