### ISSUE TITLE
Timezone 

### ISSUE THREAD

**Issue by Hims2** [spritsail/fivem#63]
Hi, there,
Is it possible to change the timezone?
Thanks

**Comment by frebib** [comment]
Full disclosure: I haven't tried this and I'm suggesting it straight from memory, but I'm 80% it should work.

I _would recommend_ against using anything other than UTC on a server. It may seem like a good idea to have all logs in localtime, but daylight savings, and timezone changes can confuse you and the computer. UTC is really the only timezone that should ever be used on a server.. but I won't stop you:

You can mount a timezone file into the container under `/etc/localtime` and that should do it.
```
docker run --volume /usr/share/zoneinfo/<Region>/<City>:/etc/localtime:ro ... spritsaill/fivem
```
or the compose equivalent

**Comment by frebib** [comment]
Closing due to lack of response
