### ISSUE TITLE
Yarn in Server Fivem

### ISSUE THREAD

**Issue by harshit2121** [spritsail/fivem#64]
Today i try to create an server but issues arise of Yarn and keep it restarting amd same error
![image](https://github.com/spritsail/fivem/assets/135013888/1c9ac441-7c76-42f9-88f8-9cb9e34d52e8)

**Comment by frebib** [comment]
This looks like a fivem issue and/or something broken with your network. The forum is probably the best place to get help https://forum.cfx.re/
