### ISSUE TITLE
Adding Scripts to FxServer 

### ISSUE THREAD

**Issue by Lking7** [spritsail/fivem#65]
This is a completely foreign language that I am trying to learn as quick and easy as I possibly can. I have searched all over google, YouTube, Reddit, etc. and have yet to find information and steps that are helpful to beginners! I have followed videos step by step and my resources still are not appearing on my txadmin resource log. The server is up and I have my scripts sitting on my desktop as well as my server.cfg pulled up yet when I copy  the name and add it to server.cfg with the word ensure and the file name of script and save it, it doesn’t show up in the txadmin “resource log”. I have to be doing something wrong here?! I am a visual learner, yet I still seem to be doing something wrong in the steps I’m taking. Please please anyone reach out and help a desperate person out!! I greatly appreciate any and all help, comments, recommendations..all of it! Thanks

**Comment by frebib** [comment]
This sounds like a fivem issue, not an issue with the container. You're probably best asking for help on the forum
https://forum.cfx.re/
