### ISSUE TITLE
Docker Hub description needs to be updated

### ISSUE THREAD

**Issue by Phyremaster** [spritsail/fivem#7]
The Docker Hub description does not match the README.md here on GitHub, meaning that users basing their configuration off of the command in that description will encounter issues that have already been closed here (namely the SIGSEGV that drove me insane all day).

**Comment by Adam-Ant** [comment]
Whoops, this issue fell behind the fridge and got missed for 6 months. Apologies. The Docker Hub readme should be auto updating, but Docker gonna Docker, so I've updated it manually.

**Comment by frebib** [comment]
I've added a CI step to automatically update the DH README on every push. Better late than never :)
Thanks for the report
