### ISSUE TITLE
POLICE / BODYGUARD PEDS don't shoot when onesync off

### ISSUE THREAD

**Issue by SkyViewBlobio** [spritsail/fivem#70]
Hello, 
I wanted to report issues ive noticed with the NPC's when not using onesync. If onesync is turned off, police / bodyguards of other players won't shoot at other players or the wanted player. 

When we however turn onesync on or use Legacy the ai will shoot at the player if wanted however the bodyguards summoned by the player or spawned by the server / recruited by the player get confused and shoot at their original recruiter.

**Comment by Adam-Ant** [comment]
Hey there. We just maintain a Docker container for FiveM - this is not an official FiveM support forum, nor do we have the expertise to assist :sweat_smile: 

I'd suggest either speaking to the dev for whatever plugin adds bodyguards, or post on the [FiveM forums](https://forum.cfx.re/) for help.
