### ISSUE TITLE
cant load in map

### ISSUE THREAD

**Issue by netixc** [spritsail/fivem#74]
hello i installed this and then added the QB mods, when i start up the game and make my char, its stuck in loading screen and i get 

```
Client -> server connection timed out. Please try again later.

Timeout info: game=8.69 ±2.39 ~0, recv=14.56 ±6.41 ~25, send=17.19 ±12.30 ~8
```

any idea what the problem is ?

**Comment by frebib** [comment]
This is not a forum for Fivem software issues. Please direct your question at https://forum.cfx.re/

**Comment by frebib** [comment]
@netixc we're merely repackaging fivem's build artifacts verbatim. With the exception of some very specific launch issues, there's nothing we can help with, sorry. We're simply the messengers. I hope you understand
